version: "3.9"

services:
  python:
    container_name: graph_kernel_convolution
    build:
      context: ./
    volumes:
      - ./:/script
    working_dir: /script
    environment:
      - TZ=UTC
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
